import { makeStyles } from '@material-ui/core/styles';

export default makeStyles(() => ({
  addTokenButton: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    bottom: 140,
    right: 24,
    position: 'absolute',
    borderRadius: 42,
    height: 42,
    paddingLeft: 8,
    paddingRight: 8,
    backgroundColor: '#FFFFF',
    cursor: 'pointer',
    border: 2,
    borderStyle: 'solid',
    borderColor: '#A0A3A9',
    gap: 4,
  },
  addNftButton: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    bottom: 82,
    right: 24,
    position: 'absolute',
    borderRadius: 42,
    height: 42,
    padding: 5,
    backgroundColor: '#FFFFF',
    border: 2,
    borderStyle: 'solid',
    borderColor: '#A0A3A9',
    cursor: 'pointer',
    gap: 4,
  },
  background: {
    width: '100%',
    height: 595,
    zIndex: 5,
    position: 'absolute',
    top: 0,
    right: 0,
  },
  selectorContainer: {
    display: 'flex',
    flexDirection: 'column',
    width: 250,
    padding: '20px 20px 0 20px',
    position: 'absolute',
    top: 50,
    right: 10,
    background: '#FFFFFF',
    borderRadius: 6,
    // boxShadow: SHADOW_1,
    zIndex: 10000,
  },
  selectorHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  networksContainer: {
    display: 'flex',
    flexDirection: 'column',
    zIndex: 10,
    maxHeight: 330,
    overflow: 'auto',
  },
}));
